# netlify.toml

[build]
  command = "npm run build"
  publish = "out"
  
  # Optional: if you want to specify the build environment variables
  [build.environment]
    NODE_VERSION = "16"  # or any specific version that works with your build

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/admin/*"
  to = "https://your-site.netlify.app/admin/:splat"
  status = 200
  force = true
