backend:
  name: git-gateway
  branch: main
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  # (même contenu que ci-dessus)
  - name: "projects"
    label: "Projets"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
  - name: "about"
    label: "À propos"
    folder: "content"
    file: "about.md"
    create: false
    fields:
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
